DROP DATABASE IF EXISTS Summary;
CREATE DATABASE Summary;
USE Summary;

CREATE TABLE login(
   Username VARCHAR(50) NOT NULL UNIQUE,
   userPassword VARCHAR(50) NOT NULL,
   LoginID VARCHAR(50) NOT NULL PRIMARY KEY UNIQUE
);

CREATE TABLE loginData(
  DataID VARCHAR(50) NOT NULL UNIQUE,
  LoginID VARCHAR(50) NOT NULL UNIQUE,
  CONSTRAINT LoginDataID PRIMARY KEY (DataID, LoginID)
  
);

CREATE TABLE dataTable(
  DataName VARCHAR(50),
  Amount INT NOT NULL,
  Desciption VARCHAR(200),
  DataID INT NOT NULL PRIMARY KEY UNIQUE
);

CREATE TABLE dateTable(
  isDay INT,
  isMonth INT,
  isYear INT,
  DateID INT NOT NULL PRIMARY KEY UNIQUE
);

CREATE TABLE dateData(
  DataID INT NOT NULL UNIQUE,
  DateID INT NOT NULL UNIQUE,
  CONSTRAINT DateDataID PRIMARY KEY (DataID, DateID),
  FOREIGN KEY (DateID) REFERENCES dateTable(DateID),
  FOREIGN KEY (DataID) REFERENCES dataTable(DataID)
);

